project:
  type: website
  output-dir: docs

website:
  image: "assets/abstrave.png"
  favicon: "assets/favicon.png"
  navbar:
    logo: "assets/abstrave.png"
    logo-alt: "logo"
    left:
      - text: "HOME"
        href: "index.html"
    right:
      - icon: "twitter"
        href: "https://twitter.com"
  page-footer:
    border: false
    left: "2023 Roy Francis | [GPL-3 License](https://choosealicense.com/licenses/gpl-3.0/)"
    right: "Published with [Quarto](https://quarto.org/) v<?quarto.version?>"
  site-url: "https://royfrancis.github.io/abstrave/"

format:
  html:
    quarto-required: ">=1.2.2"
    include-in-header: "assets/fonts/head.html"
    theme: "assets/css/custom.scss"
    smooth-scroll: true
    toc: true
    toc-depth: 4
    toc-location: right
    number-sections: true
    number-depth: 4
    code-fold: false
    code-tools: false
    code-copy: true
    code-overflow: wrap
    df-print: kable
    standalone: false
    fig-align: left
    title-block-banner: "assets/images/banner.jpg"
    subtitle: "Abstrave quarto theme"
    date:  last-modified
    date-format: "DD-MMM-YYYY"
    lightbox: 
      match: auto
  revealjs:
    quarto-required: ">=1.2.269"
    include-in-header: "assets/fonts/head.html"
    theme: ["default","assets/css/custom.scss"]
    width: 1280
    height: 720
    transition: "fade"
    transition-speed: "fast"
    smaller: false
    slide-number: true
    progress: true
    date:  last-modified
    date-format: "DD-MMM-YYYY"
    fig-align: left
    chalkboard: true
    title-slide-attributes:
      data-background-image: "assets/images/cover.jpg"
      data-background-size: "cover"
      data-background-opacity: "1"
    subtitle: "Abstrave quarto theme"
    header-logo-left: ../../assets/abstrave.png
    header-logo-right: ../../assets/abstrave.png

knitr:
  opts_chunk:
    results: hold

execute:
  eval: true
  echo: true
  warning: false
  message: false
  freeze: auto

filters:
  - assets/custom.lua
  - reveal-header
  - lightbox
